name: day09-chapel
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day09/**

jobs:
  build:
    name: AoC-day09-Chapel
    runs-on: ubuntu-latest
    container: chapel/chapel:1.23.0
    steps:
    - uses: actions/checkout@v2.3.4
    - run: |
        cd day09
        ./build.sh
        ./day09
