name: day01-prolog
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day01/**

jobs:
  build:
    name: AoC-day01-prolog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day01
        nix-shell --run './build.sh && ./day01'
