name: day08-cl
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day08/**

jobs:
  build:
    name: AoC-day08-CommonLisp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day08
        ./run.sh
