name: day03-forth
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day03/**

jobs:
  build:
    name: AoC-day03-forth
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day03
        ./run.sh
