name: day14-lua
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day14/**

jobs:
  build:
    name: AoC-day14-lua
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: |
        cd day14
        ./run.sh
