name: day15-racket
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day15/**

jobs:
  build:
    name: AoC-day15-racket
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: |
        cd day15
        ./test.sh
        ./run.sh
