name: day12-perl
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day12/**

jobs:
  build:
    name: AoC-day12-perl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day12
        ./day12.pl
