name: day18-kotlin
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - "day18/**"

jobs:
  build:
    name: AoC-day18-kotlin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day18
        ./build.sh
        ./run.sh



