name: day17-crystal
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - "day17/**"

jobs:
  build:
    name: AoC-day17-crystal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day17
        ./build.sh
        ./day17
        ./day17b


