name: day19-nim
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - "day19/**"

jobs:
  build:
    name: AoC-day19-nim
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day19
        ./build.sh
        ./day19



