name: day11-d
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - day11/**

jobs:
  build:
    name: AoC-day11-D
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day11
        ./build.sh
        ./day11
