name: day20-zig
on:
  workflow_dispatch:
  push:
      branches:
        - master
      paths:
        - "day20/**"

jobs:
  build:
    name: AoC-day20-zig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        cd day20
        ./build.sh
        ./test.sh
        ./day20



